[features]
seeds = false
skip-lint = false

[programs.localnet]
app = "8yCmCyhDsLzof54Pbuj2dBxAKSyLosdFcR7Aov894NJk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "yarn test-program"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
rpc_port = 8888

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" # Token Program

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" # Token-2022 Program

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" # Associated Account Program

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # Token Metadata Program
