[features]
seeds = false
skip-lint = false

[programs.localnet]
app = "9eAsSSyUEkPwYcTAWpf9MSYboarjv1J3vKWz8q9q9VSe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test-program"
