[features]
seeds = false
skip-lint = false

[programs.localnet]
app = "AHScsmJEzPyCPEpYqS66C3zkoEgoKscR6p4Rkp8xZoAN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test-program"
